#!/bin/bash

set -e -x

mkdir -p "$T"/build-gcc
cd "$T"/build-gcc/

rm -f .have-build .have-install
if ! test -f .have-configure; then
  (rm -f "$T"/source-gcc/newlib &&
  ln -vs "$T"/source-newlib/newlib "$T"/source-gcc/newlib &&
  rm -f "$T"/install/nvptx-none/usr &&
  mkdir -p "$T"/install/nvptx-none &&
  ln -vs . "$T"/install/nvptx-none/usr &&
  # Without --disable-sjlj-exceptions:
  #   checking whether to use setjmp/longjmp exceptions... unknown
  #   configure: error: unable to detect exception model
  #   make[1]: *** [configure-target-libgcc] Error 1
  # What about --enable-newlib-io-long-long?
  "$T"/source-gcc/configure \
    --target=nvptx-none \
    --prefix= \
    --enable-languages=c,c++,fortran \
    --enable-werror \
    --enable-checking=yes \
    CC='gcc -m64 -Wl,-rpath,'$SCB/i686-pc-linux-gnu/lib64 \
    CXX='g++ -m64 -Wl,-rpath,'$SCB/i686-pc-linux-gnu/lib64 \
    --enable-linker-plugin-flags='CC=gcc\ -m32\ -Wl,-rpath,'$SCB/i686-pc-linux-gnu/lib \
    --enable-linker-plugin-configure-flags=--host=i686-pc-linux-gnu \
    --with-sysroot=/nvptx-none \
    --with-build-sysroot="$T"/install/nvptx-none \
    --with-build-time-tools="$T"/install/nvptx-none/bin \
    --disable-sjlj-exceptions \
    --enable-newlib-io-long-long \
    $CONFIGURE_ &&
  touch .have-configure) 2>&1 | tee -a log_build
fi
test -f .have-configure
(make "$@" &&
touch .have-build) 2>&1 | tee -a log_build
test -f .have-build
