#!/bin/bash

set -e -x

mkdir -p "$T"/build-gcc
cd "$T"/build-gcc/

rm -f .have-build .have-install
if ! test -f .have-configure; then
  ("$T"/source-gcc/configure \
    --prefix= \
    --disable-bootstrap \
    --enable-languages=c,c++,fortran,lto \
    --enable-werror \
    --disable-multilib \
    CC='gcc -m64 -Wl,-rpath,'$SCB/i686-pc-linux-gnu/lib64 \
    CXX='g++ -m64 -Wl,-rpath,'$SCB/i686-pc-linux-gnu/lib64 \
    --enable-linker-plugin-flags='CC=gcc\ -m32\ -Wl,-rpath,'$SCB/i686-pc-linux-gnu/lib \
    --enable-linker-plugin-configure-flags=--host=i686-pc-linux-gnu \
    --with-sysroot= \
    $CONFIGURE_ &&
  touch .have-configure) 2>&1 | tee -a log_build
fi
test -f .have-configure
(make "$@" &&
touch .have-build) 2>&1 | tee -a log_build
test -f .have-build
