#!/bin/bash

set -e -x

cd "$T"/build-gcc-offload-nvptx-none/

rm -f .have-install
(make DESTDIR="$T"/install/offload-nvptx-none "$@" install &&
touch .have-install) 2>&1 | tee -a log_install
test -f .have-install
