#!/bin/sh

set -e -x

. ./ENV
./BUILD-gcc-offload-x86_64-intelmicemul-linux-gnu "$@"
#./TEST-gcc-offload-x86_64-intelmicemul-linux-gnu "$@"
./INSTALL-gcc-offload-x86_64-intelmicemul-linux-gnu "$@"
./BUILD-gcc "$@"
./TEST-gcc "$@"
./INSTALL-gcc "$@"
