#!/bin/bash

set -e -x

cd "$T"/build-gcc-offload-x86_64-intelmicemul-linux-gnu/

# Default RUNTESTFLAGS; extendable by RUNTESTFLAGS_.
RUNTESTFLAGS=''
# Default target; overridden by any argument not matching -* or *=*.
default_target=check
for arg; do
  case $arg in
    RUNTESTFLAGS_=*) RUNTESTFLAGS="$RUNTESTFLAGS ${arg#RUNTESTFLAGS_=}";;
    -* | *=*) :;;
    *) default_target=;;
  esac
done
(make -k RUNTESTFLAGS="$RUNTESTFLAGS" "$@" $default_target || :) 2>&1 | tee -a log_test
