#!/bin/bash

set -e -x

cd "$T"/build-gcc-offload-nvptx-none/

# Default target; overridden by any argument not matching -* or *=*.
default_target=check
for arg; do
  case $arg in
    -* | *=*) :;;
    *) default_target=;;
  esac
done
(make -k RUNTESTFLAGS='--target_board=nvptx-none-run' "$@" $default_target || :) 2>&1 | tee -a log_test
